apiVersion: v1
kind: Service
metadata:
  name: contractsbpm-service
  labels:
    app: contractsbpm-service
spec:
  type: LoadBalancer
  externalIPs:
  - 15.160.37.161
  ports:
  - port: 80  # Service port number
    targetPort: 8080  # Port number exposed by the container
    nodePort: 31118 # The real port number of the node
  selector:
    app: contractsbpm-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contractsbpm-service-deployment
spec:
  selector:
    matchLabels:
      app: contractsbpm-service
  template:
    metadata:
      labels:
        app: contractsbpm-service
    spec:
      containers:
      - image: richizana/contractsbpm-services:latest
        name: contractsbpm-container
        ports:
        - containerPort: 8080