apiVersion: v1
kind: Service
metadata:
  name: contractsbpm
  labels:
    app: contractsbpm
spec:
  type: LoadBalancer
  externalIPs:
  - ${worker_ip}
  ports:
  - port: 80  # Service port number
    targetPort: 8080  # Port number exposed by the container
    nodePort: 31117 # The real port number of the node
  selector:
    app: contractsbpm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contractsbpm-deployment
spec:
  selector:
    matchLabels:
      app: contractsbpm
  template:
    metadata:
      labels:
        app: contractsbpm
    spec:
      containers:
      - image: richizana/contractsbpm-services:latest
        name: contractsbpm-container
        ports:
        - containerPort: 8080