apiVersion: v1
kind: Service
metadata:
  name: customersdata-service
  labels:
    app: 
spec:
  type: LoadBalancer
  externalIPs:
  - 18.102.93.215
  ports:
  - port: 80  # Service port number
    targetPort: 8080  # Port number exposed by the container
    nodePort: 31117 # The real port number of the node
  selector:
    app: 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customersdata-service-deployment
spec:
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - image: richizana/customersdata-services:latest
        name: customersdata-container
        ports:
        - containerPort: 8080