apiVersion: v1
kind: Service
metadata:
  name: customersdata-service
  labels:
    app: customersdata-service
spec:
  type: LoadBalancer
  externalIPs:
  - 18.102.77.112
  ports:
  - port: 80 # Service port number
    targetPort: 8080 # Port number exposed by the container
    nodePort: 31119 # The real port number of the node
  selector:
    app: customersdata-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customersdata-service-deployment
spec:
  selector:
    matchLabels:
      app: customersdata-service
  template:
    metadata:
      labels:
        app: customersdata-service
    spec:
      containers:
      - name: customersdata-container
        image: richizana/customersdata-services:latest
        ports:
        - containerPort: 8080