apiVersion: v1
kind: Service
metadata:
  name: mysql-contractsbpm
  namespace: default
spec:
  type: LoadBalancer
  externalIPs:
  - 18.102.84.229
  ports:
  - port: 3306
    nodePort: 31562
  selector:
    app: mysql-contractsbpm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-contractsbpm
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: richizana/contractsbpm-db
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_PASSWORD
          value: rootpassword
        - name: MYSQL_USER
          value: root
        - name: MYSQL_DATABASE
          value: bpmengine
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-contractsbpm-persistent-storage
          mountPath: /var/lib/mysql-contractsbpm
      volumes:
      - name: mysql-contractsbpm-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-contractsbpm-pv-claim