apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  type: LoadBalancer
  externalIPs:
  - 15.160.181.16
  ports:
  - port: 3306
    nodePort: 31563
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
    strategy:
    type: Recreate
  template:
    metadata:
    labels:
        app: mysql
    spec:
      containers:
      - image: richizana/todosmanagerservice-db
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: manager
        - name: MYSQL_PASSWORD
          value: manager{line.separator}        - name: MYSQL_USER{line.separator}          value: manager{line.separator}        - name: MYSQL_DATABASE{line.separator}          value: todos{line.separator}        ports:{line.separator}        - containerPort: 3306{line.separator}          name: mysql{line.separator}        volumeMounts:{line.separator}        - name: mysql-persistent-storage{line.separator}          mountPath: /var/lib/mysql{line.separator}      volumes:{line.separator}      - name: mysql-persistent-storage{line.separator}        persistentVolumeClaim:{line.separator}          claimName: mysql-pv-claim