apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-test
spec:
  ingressClassName: nginx
  rules:
  - host: 15.160.115.212
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todos-tomcat
            port:
              number: 88
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todos-manager
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mysql
            port:
              number: 3306