apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: ec2-15-161-175-169.eu-south-1.compute.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: CustomerData
            port:
              number: 88
      - path: /
        pathType: Prefix
        backend:
          service:
            name: Contracts
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ContractsBPM
            port:
              number: 3306
      - path: /
        pathType: Prefix
        backend:
          service:
            name: DB-ContractsBPM
            port:
              number: 31563
      - path: /
        pathType: Prefix
        backend:
          service:
            name: DB-CustomerData
            port:
              number: 31564
