apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: http://ec2-15-161-175-169.eu-south-1.compute.amazonaws.com/
    http:
      paths:
      - path: /
        backend:
          serviceName: todosmanagerservice #obviously point this to a valid service + port
          servicePort: 80
