apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytodos-deployment
spec:
  selector:
    matchLabels:
      app: mytodos
  template:
    metadata:
      labels:
        app: mytodos
    spec:
      containers:
      - name: mytodos-container
        image: richizana/mytodos:1.0
        ports:
        - containerPort: 8888