apiVersion: v1
kind: Service
metadata:
  name: service.todosmanagerservice
  labels:
    app: service.todosmanagerservice
spec:
  type: LoadBalancer
  externalIPs:
  - 35.152.57.159
  ports:
  - port: 88 # Service port number
    targetPort: 8080 # Port number exposed by the container
    nodePort: ${port} # The real port number of the node
  selector:
    app: service.todosmanagerservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service.todosmanagerservice-deployment
spec:
  selector:
    matchLabels:
      app: service.todosmanagerservice
  template:
    metadata:
      labels:
        app: service.todosmanagerservice
    spec:
      containers:
      - name: todosmanagerservice-container
        image: richizana/todosmanagerservice:latest
        ports:
        - containerPort: 8888