apiVersion: v1
kind: Service
metadata:
  name: todosmanagerservice
  labels:
    app: todosmanagerservice
spec:
  type: NodePort
  ports:
  - port: 80  # Service port number
  selector:
    app: todosmanagerservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todosmanagerservice-deployment
spec:
  selector:
    matchLabels:
      app: todosmanagerservice
  template:
    metadata:
      labels:
        app: todosmanagerservice
    spec:
      containers:
      - image: richizana/todosmanagerservice-services:latest
        name: todosmanagerservice-container

