apiVersion: v1
kind: Service
metadata:
  name: todosmanagerservice-service
  labels:
    app: todosmanagerservice-service
spec:
  type: LoadBalancer
  externalIPs:
  - 15.160.104.166
  ports:
  - port: 88 # Service port number
    targetPort: 8080 # Port number exposed by the container
    nodePort: 31117 # The real port number of the node
  selector:
    app: todosmanagerservice-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todosmanagerservice-service-deployment
spec:
  selector:
    matchLabels:
      app: todosmanagerservice-service
  template:
    metadata:
      labels:
        app: todosmanagerservice-service
    spec:
      containers:
      - name: todosmanagerservice-container
        image: richizana/todosmanagerservice:latest
        ports:
        - containerPort: 8888