apiVersion: v1
kind: Service
metadata:
  name: todosmanagerservice_service
  labels:
    app: todosmanagerservice_service
spec:
  type: LoadBalancer
  externalIPs:
  - 18.102.44.66
  ports:
  - port: 88 # Service port number
    targetPort: 8080 # Port number exposed by the container
    nodePort: ${port} # The real port number of the node
  selector:
    app: todosmanagerservice_service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todosmanagerservice_service-deployment
spec:
  selector:
    matchLabels:
      app: todosmanagerservice_service
  template:
    metadata:
      labels:
        app: todosmanagerservice_service
    spec:
      containers:
      - name: todosmanagerservice-container
        image: richizana/todosmanagerservice:latest
        ports:
        - containerPort: 8888